name:       sgf-xmonad-modules
version:    '1.5.0'
synopsis:   sgf's xmonad modules
category:   Graphics
author:     sgf
maintainer: sgf.dma@gmail.com
license:    BSD3
github:     sgf-dma/sgf-xmonad-modules

dependencies:
- base
- mtl
- transformers
- tagged
- filepath
- directory
- unix
- containers
- process
- utf8-string
- X11
- xmonad
- string-transform
- xmonad-contrib
- xmonad-entryhelper
- sgf-haskell-common
ghc-options: -Wall

library:
  source-dirs: src
